### ISSUE TITLE
support symfony 6

### ISSUE THREAD

**Issue by douglasjam** [Codeception/module-filesystem#14]
Having the following dependency blocks the usage of Symfony 6
- "symfony/finder": ">=3.4 <6.0"

**Comment by Naktibalda** [comment]
`codeception/codeception` doesn't support Symfony 6 either.

It is very likely that supporting Symfony 6 will require code changes.

**Comment by douglasjam** [comment]
I see, I've also checked that Codeception 5 is about to be released. Just waiting for Phpunit 10 to be ready. Feel free to close it if u don't need it for control.

**Comment by Naktibalda** [comment]
2.0.1 supports symfony/finder v6.

https://github.com/Codeception/module-filesystem/releases/tag/2.0.1
