### ISSUE TITLE
Too early for PHP 8 requirement

### ISSUE THREAD

**Issue by winternet-studio** [Codeception/module-filesystem#21]
It's way too early to make PHP 8 a requirement! There are still LOTS of 7.3 and 7.4 sites out there in production. And making them PHP 8 compatible is NOT always an easy thing. So please relax your requirements so you don't create unnecessary problems and headaches for us who have been using your code for a long time.

**Comment by Naktibalda** [comment]
You are welcome to use 2.* on PHP 7.4 and 1.* on older versions with Codeception 4.
